const mongoose = require('mongoose');

const chatbotInteractionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, // Reference to the User model
  prompt: { type: String, required: true }, // The question or message sent by the user
  response: { type: String, required: true }, // The response generated by the chatbot
  timestamp: { type: Date, default: Date.now } // When the interaction occurred
});

const ChatbotInteraction = mongoose.model('ChatbotInteraction', chatbotInteractionSchema);

module.exports = ChatbotInteraction;